name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Cache Bazel
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/bazel
        key: ${{ runner.os }}-bazel-${{ hashFiles('.bazelrc', '.bazelversion', 'WORKSPACE*', 'MODULE.bazel') }}
        restore-keys: |
          ${{ runner.os }}-bazel-
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential curl netcat-openbsd python3
    
    - name: Build all targets
      run: |
        bazel build //...
    
    - name: Test bazel test runner
      run: |
        bazel test //tests/smoke:smoke_test
